### ISSUE TITLE
Supprimer événement

### ISSUE THREAD

**Issue by Raphlmarc95** [Raphlmarc95/EXPERTPLUS#10]
En tant que Membre, je souhaite Supprimer un événement que j'avais créer sur le site Biblioplus.

**Comment by Beoly** [comment]
Pré-conditions: Un membre est authentifié dans BiblioPlus et accède à la page événement.

Déclencheur: L'auteur de l'événement clique sur "Supprimer événement".

Déroulement: 
L'auteur de l'événement clique sur le bouton "supprimer événement". Biblioplus lui demande une confirmation avec le message suivant:  "Êtes-vous certains de vouloir supprimé cet événement". "Supprimer événement" ou "Annuler".
- Quand l'auteur clique sur "Supprimer événement", BiblioPlus supprime l’événement.
- Quand l'auteur clique sur "Annuler", BiblioPlus lui retourne à la page d’événement.

Post-condition: "Evénement supprimé".
