### ISSUE TITLE
Télécharger ouvrage

### ISSUE THREAD

**Issue by Raphlmarc95** [Raphlmarc95/EXPERTPLUS#12]
En tant que membres, j'aimerais avoir en ma propriété les livres que j'aime sur le site de Biblioplus (Télécharger ouvrage).

**Comment by Beoly** [comment]
Pré-conditions: Un membre authentifié dans BiblioPlus aimerait télécharger un ouvrage.

Déclencheur: L'auteur clique sur l'onglet "Téléchargement d'ouvrage".

Déroulement:
- Le membre clique sur la page collection.
- Il clique sur l'ouvrage qu'il veut télécharger.
- L'ouvrage en question sera ouverte 
- Le membre clique sur l'onglet de téléchargement du navigateur.

Post-condition: "Ouvrage télécharger".
