### ISSUE TITLE
Créer compte

### ISSUE THREAD

**Issue by Raphlmarc95** [Raphlmarc95/EXPERTPLUS#15]
En tant que VISITEUR, je veux CRÉER UN COMPTE dans Biblioplus, afin de partager mes aventures de lectures et d'écritures avec d'autres lecteurs.

**Comment by Raphlmarc95** [comment]
Pré-conditions: Un internaute visite le site BiblioPlus et aimerait devenir membre.
Déclencheur: L'internaute clique sur le bouton "créer compte".
Déroulement: 
1. BiblioPlus affiche la fenêtre de création de compte en indiquant les champs obligatoires (marqués par *champs*):
   - *Choisir photo*: 90 caractères.
   - *Nom complet*: 50 caractères.
   - *Nom d'utilisateur*: 15 caractères.
   - *Mot de passe*: 8 caractères (minimum).
   - *Confirmation du mot de passe*: 8 caractères(minimum).
   - *Votre adresse mail*: 100 caractères.
   - *Date de naissance* (format DATE):  JJ/MM/AAAA (Date).
   - *Sexe*: 10 caractères.
   - *Inscrire en tant que*:  Choisir
   - *Une petite description*: Texte.
1. L'internaute ne  remplit pas les champs affichés et  presse sur "Valider".
Un message d'erreur s'affichera:
    - "Le champ nom complet peut contenir que des caractères alphabétique Ex.: (Bergele Franck).", 
   - "Le champ nom d'utilisateur peut contenir que des caractères alphanumériques, des caractères de soulignement et des traits d'union.",
   -  "Le champ mot de passe est requis",
   - "Le champ Email est requis", 
   - "La Date de naissance est requis", 
   - "Il faut s'inscrire en tant qu'auteur ou un simple membre".
1. L'internaute remplit les principaux champs.
BiblioPlus valide que les champs sont bien remplis, un message d'erreur s'affichera si le client ne respecte pas les specifications suivantes:
   - Pour le nom complet: "Le champ nom complet peut contenir que des caractères alphabétique Ex.: (Bergele Franck).",
   - Pour le nom d'utilisateur "Le champ nom d'utilisateur doit contenir au moins 6 caractères"
   - Pour le Mot de passe "Le champ mot de passe doit contenir au moins 8 caractères".
   - Pour le champ confirmation mot de passe
   - Pour l' Email "Le champ email doit contenir une adresse email valide.".
1. L'internaute  remplit les champs avec un nom d'utilisateur qui existe déjà et  presse sur "Enregistrer". BiblioPlus notifiera "nom d'utilisateur existant".
1. L'internaute  remplit les champs correctement et presse sur "Enregistrer".
1. BiblioPlus envoie un courriel de confirmation pour que le nouveau membre devienne actif avec ce message "Un email de confirmation vous a  été envoyé".
   - Objet du courriel: "Création de votre compte sur BiblioPlus"
   - Texte du courriel: "Cliquer sur ce lien afin de confirmer votre compte".
1. L'internaute ne clique pas sur le lien: "Compte non confirmé".
   L'internaute clique sur le lien: "Compte confirmé".

Post-condition: "membre enregistré".

**Comment by strudelauxpommes** [comment]
_Cas de tests_:
1. Créer une fiche où tous les champs obligatoires sont remplis adéquatement.
2. Créer une fiche dont le nom utilisateur existe déjà --> Message "Ce nom utilisateur existe déjà, svp veuillez en choisir un autre".
3. Créer une fiche dont certains champs obligatoires sont non remplis --> Message"..."
4. Date invalide --> Message "..."

**Comment by Beoly** [comment]
N.B. Le champ questionnaire concerne uniquement les auteurs. Il doit absolument le remplir.
