### ISSUE TITLE
Formater les champs

### ISSUE THREAD

**Issue by Raphlmarc95** [Raphlmarc95/EXPERTPLUS#16]
Biblioplus souhaite que toutes les informations qui vont être inscrites soient correctes.

**Comment by Raphlmarc95** [comment]
Pré-conditions: Un visiteur ou un membre tente de remplir les champs et  de  les enregistrés.

Déclencheur: 
- Un visiteur ou un membre tente de valider une transaction dont les champs remplis ne respectent pas  les formats prédéfinis.

Déroulement:
- Biblioplus demande de remplir les champs correctement.

Post-condition: Enregistrement reussi.

**Comment by strudelauxpommes** [comment]
Fonctionnalité non requise.
