### ISSUE TITLE
Poster un sujet(FORUM)

### ISSUE THREAD

**Issue by Raphlmarc95** [Raphlmarc95/EXPERTPLUS#23]
En tant que MEMBRE, je veux "Poster un sujet" sur le  "FORUM" de Biblioplus.

**Comment by Beoly** [comment]
Pré-conditions: Un MEMBRE est authentifié sur Biblioplus et souhaite Poster un sujet sur le FORUM.

Déclencheur: Le MEMBRE clique sur le bouton "Nouveau sujet".

Déroulement:
Biblioplus affiche la fenêtre pouvant permettre de poster un sujet en indiquant des champs obligatoires à remplir:
  -*Sujet*: 90 caratères.
  -*Catégorie*: Selection.
  -*Contenu*: Texte(infini).
-Le MEMBRE ne remplit pas les champs obligatoires et clique sur Enregistrer. Biblioplus affichera "Le champ sujet est requis".
"Le champ categorie est requis".
"Le champ contenu est requis".
-Le MEMBRE effectue une operation sur l'un des trois. Biblioplus notifiera que les deux autres sont requis.
-Le MEMBRE remplit les champs et fait la sélection d'une categorie. Le MEMBRE sera dirigé vers la page FORUM avec la possibilité de voir la date et l'heure de la création du poste, le nombre de personne ayant commenté le sujet et sa catégorie.

Post-condition: "Sujet posté".
