### ISSUE TITLE
J'aime un (e) (poste, commentaire, publication)

### ISSUE THREAD

**Issue by Franckoberg** [Raphlmarc95/EXPERTPLUS#27]
En tant que MEMBRE (auteur ou lecteur), je veux AIMER un(e) (poste, commentaire, publication) dans Biblioplus.

**Comment by Beoly** [comment]
Pré-conditions: Un visiteur est authentifie sur le site BiblioPlus et aimerait AIMER un(e) (poste, commentaire, publication).

Déclencheur: L'internaute clique sur l'onglet j'aime.

Déroulement:
Le membre une fois authentifié sur le site Biblioplus clique sur l'onglet  qui se trouve en dessous d'un(e) (poste, commentaire, publication) "J'AIME" qui deviendra autaumatiquement bleu.

Post-condition: (Poste, commentaire, publication) AIMER.
