### ISSUE TITLE
Mot de passe oublier

### ISSUE THREAD

**Issue by Raphlmarc95** [Raphlmarc95/EXPERTPLUS#4]
En tant que visiteur, je souhaite créer un compte afin d’être un membre(Auteurs ou Lecteurs) de Biblioplus.

**Comment by Beoly** [comment]
Pré-conditions:  Un visiteur souhaite effectuer une action sur Biblioplus.

Déclencheur: Le visiteur clique sur le bouton "Créer compte".

Déroulement: 
-Une fois cliquer sur le bouton, des champs seront ouvert devant lui afin de les remplir, ensuite "Valider" ces informations.
-Biblioplus lui demandera d'aller confirmer son compte sur le mail qu'il avait donnée.
-Apres sa confirmation, il sera dirigé sur son compte Biblioplus
Post-condition: Compte créer.
