### ISSUE TITLE
Modifier événement

### ISSUE THREAD

**Issue by Raphlmarc95** [Raphlmarc95/EXPERTPLUS#9]
En tant que Membre, je veux "Modifier un Evénement" que j'ai créer dans Biblioplus.

**Comment by Beoly** [comment]
Pré-conditions: Un Membre authentifié dans Biblioplus souhaite modifier un événement qu'il avait créé dans BiblioPlus.

Déclencheur: L'auteur de l'événement clique sur "Modifier événement".

Déroulement: 
- L'auteur de l'événement clique sur l'événement qu'il avait créer dans la page événement.
-L'événement en question sera affiché et le membre cliquera sur, "Modifier événement".
-BiblioPlus demande une confirmation avec le message suivant: "Voulez-vous apporter de nouvelles modification a cet évenement ?". "Modifier événement" ou "Annuler"
 - Quand l'auteur clique sur "Modifier événement".
 - Des champs seront ouvert afin de porter de nouvelles modifications.
 - Ensuite, BiblioPlus affichera un message  "Evénement modifier".
 - Quand l'auteur clique sur "Annuler", Biblioplus lui retourne à la page d’événement.

Post-condition: Événement modifier.
